---
Name: silverstripe-seeder
---

suppress_warning: true

---
Only:
  environment: 'dev'
---
Image:
  extensions:
    - SeederExtension

DevelopmentAdmin:
  registered_controllers:
    seed:
      controller: DevSeedController
    unseed:
      controller: DevUnseedController
