---
Name: silverstripe-seeder
---

Seeder2:
  providers:
    - 'DataTypeProvider'
    - 'FakerProvider'
    - 'ImageProvider'
    - 'ValueProvider'
  empty_shorthand_provider: 'ValueProvider'
  default_provider: 'DataTypeProvider'
  default_providers:
    Image: 'ImageProvider'

---
Only:
  environment: 'dev'
---
DevelopmentAdmin:
  registered_controllers:
    seed:
      controller: DevSeedController
    unseed:
      controller: DevUnseedController

