---
Name: silverstripe-seeder
---

Seeder:
  providers:
    - DataTypeProvider
    - FakerProvider
    - ImageProvider
    - ValueProvider
    - ObjectProvider
  empty_shorthand_provider: ValueProvider
  default_provider: DataTypeProvider
  default_providers:
    Image: ImageProvider
  default_ignores:
    SiteTree:
      - Sort
      - HasBrokenFile
      - HasBrokenLink
      - ReportClass
      - Priority
      - Version
    Member:
      - TempIDHash
      - TempIDExpired
      - RememberLoginToken
      - NumVisit
      - LastVisited
      - AutoLoginHash
      - AutoLoginExpired
      - PasswordEncryption
      - Salt
      - PasswordExpiry
      - LockedOutUntil
      - Locale
      - FailedLoginCount
      - DateFormat
      - TimeFormat
  default_values:
    SiteTree:
      ShowInMenus: 0
      ShowInSearch: 1
      CanViewType: Anyone
      CanEditType: LoggedInUsers

---
Only:
  environment: 'dev'
---
DevelopmentAdmin:
  registered_controllers:
    seed:
      controller: DevSeedController
    unseed:
      controller: DevUnseedController

