---
Name: silverstripe-seeder
After: 'framework/*', 'cms/*'
---

Seeder:
  providers:
    - DataTypeProvider
    - DateProvider
    - FakerProvider
    - HTMLProvider
    - ImageProvider
    - MemberProvider
    - ObjectProvider
    - PageTitleProvider
    - RandomObjectProvider
    - SortProvider
    - UniqueProvider
    - URLSegmentProvider
    - ValueProvider
    # tests
    - LittleGiant\SilverStripeSeeder\Tests\TestProvider
  empty_shorthand_provider: ValueProvider
  default_provider: DataTypeProvider
  default_providers:
    Image: ImageProvider
  default_ignores:
    SiteTree:
      - Sort
      - HasBrokenFile
      - HasBrokenLink
      - ReportClass
      - Priority
      - Version
    Member:
      - TempIDHash
      - TempIDExpired
      - RememberLoginToken
      - NumVisit
      - LastVisited
      - AutoLoginHash
      - AutoLoginExpired
      - PasswordEncryption
      - Salt
      - PasswordExpiry
      - LockedOutUntil
      - Locale
      - FailedLoginCount
      - DateFormat
      - TimeFormat
  default_values:
    SiteTree:
      ShowInMenus: 0
      ShowInSearch: 1
      CanViewType: Anyone
      CanEditType: LoggedInUsers


